version: '3.5'
services:
  api1: # API - Instância 01
    build: .
    hostname: api1
    depends_on:
      - db
    expose:
      - "8000"
    environment:
      RINHA_DB_HOST: db
      RINHA_DB_PORT: 5432
      RINHA_DB_USER: rinha
      RINHA_DB_PASSWORD: rinha
      RINHA_DB_NAME: rinha
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2: # API - Instância 01
    build: .
    hostname: api2
    depends_on:
      - db
    expose:
      - "8000"
    environment:
      RINHA_DB_HOST: db
      RINHA_DB_PORT: 5432
      RINHA_DB_USER: rinha
      RINHA_DB_PASSWORD: rinha
      RINHA_DB_NAME: rinha
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
  db: # Banco de dados
    image: postgres
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1.7GB'
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: rinha
      POSTGRES_USER: rinha
    volumes:
      - ./src/config/db.sql:/docker-entrypoint-initdb.d/init.sql